### ISSUE TITLE
How can I skip a genomic segment in the plot?

### ISSUE THREAD

**Issue by SentientVirus** [moshi4/pyGenomeViz#21] opened 2023-09-08 14:27 UTC
Hi,
First of all, thank you for developing this package, I have used GenoPlotR in the past, but I personally prefer to program in Python, and with PygenomeViz you can get very nice plots without changing the defaults. I am using PygenomeViz to display Blast matches, but in a few of my comparisons, there is an inserted sequence in the middle. I wanted to plot the segments before and after the insertion next to each other, but I didn't manage to do so. Instead, what I have done so far is moving the positions of the CDS and matches, and then manually editing the image. Is there an easier way to plot several segments next to each other, or to skip a segment in the plot? If not, that could be a nice new feature.

Thank you for reading this post!

**Comment by moshi4** [comment] 2023-09-08 15:13
Hi @SentientVirus,

Thanks for your interest in pyGenomeViz.

> Is there an easier way to plot several segments next to each other, or to skip a segment in the plot?

There doesn't seem to be an easy solution in pyGenomeViz.

> If not, that could be a nice new feature.

As you pointed out, I understand that it would be more convenient to be able to place multiple segments within a track in pyGenomeViz.

However, the API design of pyGenomeViz is bad, which makes it quite difficult to modify it to place multiple segments. It may be faster to redesign the API from scratch and re-implement it as new software.

For these reasons, I'm not currently considering implementing the functionality to place multiple segments in pyGenomeViz.

**Comment by moshi4** [comment] 2024-05-18 15:03
Close as the issue is resolved in major upgrade v1.0.0

**Closed by moshi4** 2024-05-18 15:03 UTC
Labels: enhancement
